# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8eeea2401a0d76b80e937c11b0e72b61d0160d39b8d08b92406e2be620468a22e1a5a2b9db09a3c453ade4a2c203136d242b018ba23011e67226dd0f8b28583

test:
  secret_key_base: b81728731898eff285aa8afbaf802ad90fff3d7038c7433b86233a176cec12f97653b8aa3a6b85726796f6bd0f23e81792e3c6fa32824471ee03c9a6f8e56dd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
